image: docker:latest

stages:
  - build
  - deploy

variables:
  REGISTRY: ghcr.io
  NODE_IMAGE_NAME: dommmin/laravel-production-node-builder
  PHP_IMAGE_NAME: dommmin/laravel-production-php
  NGINX_IMAGE_NAME: dommmin/laravel-production-nginx
  DOCKER_BUILDKIT: 1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $REGISTRY

build_node:
  stage: build
  image: docker:24.0.5
  script:
    - docker buildx create --use
    - mkdir -p docker/node docker/php
    - echo "$ENV_FILE" > docker/node/.env
    - echo "$ENV_FILE" > docker/php/.env
    - cat docker/node/.env
    - |
      docker buildx build \
        --platform linux/amd64 \
        --file docker/node/Dockerfile \
        --tag $REGISTRY/$NODE_IMAGE_NAME:latest \
        --push \
        .

build_php:
  stage: build
  image: docker:24.0.5
  needs: [build_node]
  script:
    - docker buildx create --use
    - |
      docker buildx build \
        --platform linux/amd64 \
        --file docker/php/Dockerfile \
        --tag $REGISTRY/$PHP_IMAGE_NAME:latest \
        --push \
        --build-context node=docker-image://$REGISTRY/$NODE_IMAGE_NAME:latest \
        .

build_nginx:
  stage: build
  image: docker:24.0.5
  needs: [build_node]
  script:
    - docker buildx create --use
    - |
      docker buildx build \
        --platform linux/amd64 \
        --file docker/nginx/Dockerfile \
        --tag $REGISTRY/$NGINX_IMAGE_NAME:latest \
        --push \
        --build-context node=docker-image://$REGISTRY/$NODE_IMAGE_NAME:latest \
        --build-arg HTPASSWD_USER=$HTPASSWD_USER \
        --build-arg HTPASSWD_PASS=$HTPASSWD_PASS \
        .

deploy_production:
  stage: deploy
  image: alpine:3.19
  needs: [build_node, build_php, build_nginx]
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - echo "$ENV_FILE" > .env
    - |
      echo "REGISTRY=$REGISTRY" >> .env
      echo "PHP_IMAGE_NAME=$PHP_IMAGE_NAME" >> .env
      echo "NGINX_IMAGE_NAME=$NGINX_IMAGE_NAME" >> .env
      echo "TAG=latest" >> .env
    - scp -P $SSH_PORT docker-compose.production.yml $SSH_USER@$SSH_HOST:~/laravel/docker-compose.yml
    - scp -P $SSH_PORT .env deploy.sh $SSH_USER@$SSH_HOST:~/laravel/
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd ~/laravel && chmod +x deploy.sh && ./deploy.sh"
  only:
    - main