services:
  app:
    image: ${REGISTRY}/${PHP_IMAGE_NAME}:${TAG:-latest}
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public
    networks:
      - laravel_network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "php", "artisan", "queue:work", "--once"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE_NAME}:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - laravel_storage:/var/www/storage:ro
      - laravel_public:/var/www/public:ro
    networks:
      - laravel_network
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - laravel_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_storage:
  laravel_public:
  redis_data:
