services:
  app:
    image: ${REGISTRY}/${PHP_IMAGE_NAME}:${TAG:-latest}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public
    networks:
      - laravel_network
    depends_on:
      - redis

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE_NAME}:${TAG:-latest}
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - laravel_storage:/var/www/storage:ro
      - laravel_public:/var/www/public:ro
    networks:
      - laravel_network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel_network
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: laravel_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - laravel_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.1
    container_name: laravel_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - laravel_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.1
    container_name: laravel_filebeat
    user: root
    volumes:
      - ./docker/local/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - laravel_storage:/logs:ro
      - /var/log/nginx:/nginx-logs:ro
      - /var/log/php8:/php-logs:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_storage:
  laravel_public:
  redis_data:
  esdata:
    driver: local
