version: '3.8'

services:
  app:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/supervisord.conf:/etc/supervisor/supervisord.conf
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
  redis_data:
    driver: local
