version: '3.8'

services:
  app:
    image: ${REGISTRY}/${PHP_IMAGE_NAME}:${TAG:-latest}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .env:/var/www/.env
      - laravel_storage:/var/www/storage
      - laravel_bootstrap:/var/www/bootstrap
    networks:
      - laravel_network
    depends_on:
      - db
      - redis
    user: "1000:1000"

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE_NAME}:${TAG:-latest}
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - laravel_app:/var/www:ro
      - laravel_storage:/var/www/storage:ro
      - laravel_bootstrap:/var/www/bootstrap:ro
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel_network
    ports:
      - "6379:6379"

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  laravel_app:
    driver: local
  laravel_storage:
    driver: local
  laravel_bootstrap:
    driver: local
