services:
  app:
    image: ${REGISTRY}/${PHP_IMAGE_NAME}:${TAG:-latest}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .env:/var/www/.env
      - laravel_app:/var/www
    networks:
      - laravel_network
    depends_on:
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - laravel_app:/var/www
    networks:
      - laravel_network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel_network
    ports:
      - "6379:6379"

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_app:
