version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    volumes:
      - app_data:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - laravel-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - app_data:/var/www
      - php_logs:/var/log/php-fpm
      - supervisor_logs:/var/log/supervisor
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  app_data:
  db_data:
  nginx_logs:
  php_logs:
  supervisor_logs:
