filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    fields:
      service: laravel
  - type: log
    enabled: true
    paths:
      - /nginx-logs/*.log
    fields:
      service: nginx
  - type: log
    enabled: true
    paths:
      - /php-logs/*.log
    fields:
      service: php

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "logs-%{[fields.service]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"
