server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: laravel
          __path__: /var/log/laravel/*.log

  - job_name: nginx-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log

  - job_name: php-fpm-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: php-fpm
          __path__: /var/log/php8/*.log 