global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9091']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Dodaj tu kolejne eksportery/metody zbierania metryk, np. exporter do PHP/Laravel
  # - job_name: 'php-fpm'
  #   static_configs:
  #     - targets: ['app:9253'] 